### ISSUE TITLE
NLX service (intermittently) unavailable

### ISSUE THREAD

**Issue by damm89** [GemeenteUtrecht/ZGW#561]
# Bug

Calls naar de NLX service krijgen 503 service unavailable error terug.
O.a. bij laden van een pagina's als https://zac.utrechtproeftuin.nl/core/zaken/002220647/ZAAK-2020-0000004386/, maar ook bij form submissions etc. Service is onregelmatig maar lijkt het soms toch te doen.

**Comment by sergei-maertens** [comment]
Looks like this was related to the SAN breaking change in Go 1.15, used by the NLX inway/outway. The workaround was initally to use a `GODEBUG=x509ignoreCN=0` environment variable, but this has since been fixed by the NLX team in their certportal. Re-generate your NLX certificate(s) following the docs on https://docs.nlx.io/try-nlx/retrieve-a-demo-certificate to have the SAN in the certificate.

Our infrastructure inway and outway have been updated to the latest version and certiciates have been re-generated.
